# Generated by Django 2.1.2 on 2018-11-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_ip_mac',
            name='mac',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
