# Generated by Django 2.1.2 on 2018-11-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_service', '0003_auto_20181114_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_ip_mac',
            name='is_local',
            field=models.BooleanField(default=True),
        ),
    ]
