# Generated by Django 2.1.2 on 2018-11-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client_ip_mac',
            fields=[
                ('client_mac', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('client_ip', models.GenericIPAddressField(protocol='IPv4')),
            ],
        ),
    ]
